[deps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"
MPIPreferences = "3da0fdf6-3ccc-4f1b-acd9-58baa6c99267"

[compat]
CUDA = "5.5"
IJulia = "1.25"
MPI = "0.20"
MPIPreferences = "0.1"
julia = "1.10"
